titles_collection = {
    0: {'a': ['Let a spaceship move through space at 85 percent of the speed of light. At a certain\nposition ahead of it, there is a receiver whose function is to receive signals,\nrecord the exact time of reception of these signals, and the messages they carry.\nLet the spaceship start emitting signals at regular intervals of 1 second according\nto its own clock when it is exactly 15 light-seconds away from the receiver.\nEach signal carries a message that contains information about the moment it was emitted.\nThus, message 0 indicates that the signal was emitted at time 0, message 1 at time 1, and so on.', 1],
       'b': ['At the top left of the screen, the clocks of the two systems are shown. As known from\nEinstein`s Special Theory of Relativity, at speeds close to that of light, time in\nthe moving system slows down. The factor of this slowdown is called the gamma factor,\nand for a speed of 85 percent of the speed of light, its value is approximately\n0.526782687642637. This means that for one second of time on the clock of the stationary\nsystem, a little more than 52 hundredths have passed on the clock of the moving system.\nLet the simulation begin!!!', 1]},
    
    191: {'a': ['One second according to the time on the spaceship has passed, and it emits a second\nsignal with the message 1. Determining the exact location from which this occurs is\ncritical for the accuracy of the simulation. The stationary clock of the receiver\nshows 1.91 seconds at this moment. This means that the first signal emitted by the\nspaceship is now at a distance of 1.91 light-seconds from the point it was emitted.\nSince the spaceship is moving at 85 percent of the speed of light, its position should\nbe 85 percent of the distance traveled by the first light signal.', 1]},
    
    1501: {'a': ['The receiver picks up the first signal from the spaceship with the message 0. At this\nmoment, it starts its own chronometer to measure the intervals and begins keeping\ntrack of the reception time of the signals and the messages they carry. The records\nare displayed at the top right of the screen.',1]},
    
    1763: {'a': ["At this moment, the distance between the spaceship and the receiver is zero.\nAll signals from the spaceship sent during its movement towards the\nreceiver have been received. As can be seen from the readings, the time\nintervals measured by the stationary clock are approximately equal to\n0.28 seconds. In other words, according to this clock, time in the spaceship\nflows about four times faster than its own. Let's observe what happens\nto the receiver's readings as the spaceship moves away from it." ,1]},
    
    2016: {'a': ["The tenth signal sent from the spaceship has been received. As seen from the \nreadings, the time difference between it and the previous ninth signal is\nsignificantly larger than the differences between the previous signals. This\nis due to the spaceship moving away from the receiver. This is not the full\ndifference, as between the ninth and tenth signals, the spaceship transitioned\nfrom an approaching to a receding object. The full difference will be seen\nbetween the next signals." ,1]},
    
    3528: {'a': ["End of the simulation.\nAs seen from the readings, the time interval between the signals, while the\nspaceship is moving away from the receiver, is approximately 3.5 seconds.\nThis is the interval we would get if we calculated the redshift of a body\nmoving away from the observer at 85 percent of the speed of light using the\nformula used to estimate the speed of the most distant galaxies.\nThis formula includes the gamma factor. If the simulation is correct, some\nobservations should be made and several questions should be asked.",30]}
}